"""
Live2D 桌面宠物项目配置
"""

MODEL_PATH = "./resources/models/Hiyori.model3.json"

WINDOW_WIDTH = 400
WINDOW_HEIGHT = 500
WINDOW_TITLE = "Live2D 桌宠"

FPS = 60
FRAME_INTERVAL = 1000 // FPS

EXPRESSION_HAPPY = "happy"
EXPRESSION_SERIOUS = "serious"
EXPRESSION_SLEEPY = "sleepy"

BLINK_MIN_INTERVAL = 2.0
BLINK_MAX_INTERVAL = 5.0
BLINK_DURATION = 0.3

BREATH_SPEED = 1.5
WAVE_DURATION = 2.0
